#!/usr/bin/env python3
"""l10n_vectors -- the plural-rule test vectors the l10n selftest checks our evaluator against.

A catalogue's Plural-Forms header is a C expression over n, and src/l10n/plural_expr.cpp evaluates
it. A vector is (rule, n, the form n takes); a vector whose expected form came from our own
evaluator would pass whatever that evaluator gets wrong, so the forms here come from Python's own
gettext.c2py, an implementation independent of ours.

The rules are the distinct ones languages ship: the thirteen of MTA's 43 client catalogues (whitespace
aside), plus Polish, Irish and the three-form Czech rule of GNU gettext's manual. They are short
formulas, facts of each language, written here as data. Beside them sit headers the evaluator must
refuse.

Usage:
  l10n_vectors.py            writes src/votv-coop/src/l10n/plural_vectors.inc
  l10n_vectors.py --check    exits 1 when that file differs from what this script writes
"""

import gettext
import pathlib
import re
import sys

OUT = pathlib.Path(__file__).resolve().parents[2] / "src" / "votv-coop" / "src" / "l10n" / "plural_vectors.inc"

RULES = [
    "nplurals=1; plural=0;",
    "nplurals=2; plural=(n != 1);",
    "nplurals=2; plural=(n > 1);",
    "nplurals=2; plural=(n%10==1 && n%100!=11 ? 0 : 1);",
    "nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);",
    "nplurals=3; plural=(n==1 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);",
    "nplurals=3; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 2;",
    "nplurals=3; plural=n==1 ? 0 : n==2 ? 1 : 2;",
    "nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n != 0 ? 1 : 2;",
    "nplurals=3; plural=(n==1 ? 0 : (n==0 || (n%100 > 0 && n%100 < 20)) ? 1 : 2);",
    "nplurals=4; plural=(n==1) ? 0 : (n>=2 && n<=4) ? 1 : 3;",
    "nplurals=4; plural=n%100==1 ? 0 : n%100==2 ? 1 : n%100==3 || n%100==4 ? 2 : 3;",
    "nplurals=4; plural=(n%10==1 && (n%100>19 || n%100<11) ? 0 : (n%10>=2 && n%10<=9) && "
    "(n%100>19 || n%100<11) ? 1 : n%1!=0 ? 2 : 3);",
    "nplurals=4; plural=(n==1 ? 0 : (n%10>=2 && n%10<=4) && (n%100<12 || n%100>14) ? 1 : "
    "n!=1 && (n%10>=0 && n%10<=1) || (n%10>=5 && n%10<=9) || (n%100>=12 && n%100<=14) ? 2 : 3);",
    "nplurals=4; plural=((n%10==1 && n%100!=11) ? 0 : ((n%10>=2 && n%10<=4 && (n%100<12 || n%100>14)) ? 1 : "
    "((n%10==0 || (n%10>=5 && n%10<=9)) || (n%100>=11 && n%100<=14)) ? 2 : 3));",
    "nplurals=6; plural=(n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5);",
]

N = [0, 1, 2, 3, 4, 5, 7, 11, 12, 14, 21, 22, 25, 100, 101, 102, 111, 1000000, 2 ** 63]

REFUSED = [
    "nplurals=INTEGER; plural=EXPRESSION;",      # a fresh template's placeholder
    "nplurals=0; plural=0;",
    "nplurals=9; plural=n;",
    "nplurals=2;",
    "nplurals=2; plural=n ^ 1;",                 # a token outside the grammar
    "nplurals=2; plural=(n != 1;",
    "nplurals=2; plural=n != 1 1;",              # input left over
    "nplurals=2; plural=" + "(" * 33 + "n" + ")" * 33 + ";",   # nested deeper than 32
    "nplurals=2; plural=" + "!" * 33 + "n;",
    "nplurals=2; plural=" + "n+" * 128 + "n;",   # longer than 256 characters
    "nplurals=2; plural=12345678901234567890;",  # a number of more than 19 digits
]


def expression(rule):
    m = re.search(r"plural\s*=\s*(.*?);?\s*$", rule)
    return m.group(1).rstrip(";")


def c_string(s, indent="    ", width=110):
    """A C string literal, split into adjacent literals that the compiler joins, to stay in width."""
    body = s.replace("\\", "\\\\").replace('"', '\\"')
    room = width - len(indent) - 3
    chunks = [body[i:i + room] for i in range(0, len(body), room)] or [""]
    return ("\n" + indent).join('"' + c + '"' for c in chunks)


def render():
    lines = [
        "// l10n/plural_vectors.inc -- GENERATED by .github/ci/l10n_vectors.py, never hand-edited. The",
        "// forms are Python's gettext.c2py's, an evaluator independent of src/l10n/plural_expr.cpp.",
        "",
        "constexpr const char* kRules[] = {",
    ]
    lines += ["    " + c_string(r) + "," for r in RULES]
    lines += ["};", "", "struct Vector { unsigned char rule; unsigned long long n; unsigned char form; };",
              "constexpr Vector kVectors[] = {"]
    for i, r in enumerate(RULES):
        f = gettext.c2py(expression(r))
        cells = ["{%d, %dull, %d}," % (i, n, f(n)) for n in N]
        row = "   "
        for c in cells:
            if len(row) + 1 + len(c) > 110:
                lines.append(row)
                row = "   "
            row += " " + c
        lines.append(row)
    lines += ["};", "", "constexpr const char* kRefusedRules[] = {"]
    lines += ["    " + c_string(r) + "," for r in REFUSED]
    lines += ["};", ""]
    return "\n".join(lines)


def main():
    text = render()
    if "--check" in sys.argv[1:]:
        have = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if have.replace("\r\n", "\n") != text:
            print("l10n_vectors: %s is stale -- run .github/ci/l10n_vectors.py" % OUT.name)
            return 1
        print("l10n_vectors: %s is current" % OUT.name)
        return 0
    OUT.write_text(text, encoding="utf-8", newline="\n")
    print("l10n_vectors: wrote %s (%d rules x %d n)" % (OUT.name, len(RULES), len(N)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
