#!/usr/bin/env python3
"""l10n_pot -- the mod's translation template, and the gate that keeps the call sites honest.

The template (src/votv-coop/locale/multivoid.pot) is every msgid the mod looks up, extracted from the files that may
hold player text: the allowlist below, kept by hand beside the translation layer's design and never guessed. A
contributor without the maintainer's local tools regenerates it with this script; MTA runs xgettext for the same
job, and ours is a script because the markers inside the config tables and the allowlist are ours.

Extraction reads C++ as tokens (comments and strings skipped as the compiler skips them), takes `l10n::T`,
`l10n::Tc`, `l10n::Tn`, `L10N_MARK`, `L10N_MARK_C` and `L10N_MARK_N` whose arguments are string literals, joins
adjacent literals and decodes escapes as the compiler does, and writes entries sorted by (msgctxt, msgid) with
file-name references and no line numbers, so the template changes only when a string does. A non-literal argument
(a drawer's `T(entry.name)`) is not extracted: its literal was marked where it is defined.

Usage:
  l10n_pot.py            writes the template and the pseudo-locale (locale/en_XA.po)
  l10n_pot.py --check    the gate: exits 1 on a stale template or pseudo-locale, or on any rule below

The gate's rules (the translation layer's design, WP-4):
  1. an extraction call or marker with a literal argument in a file outside the allowlist;
  2. an id-bearing ImGui widget (a function of imgui.h whose first parameter is label, name or str_id) whose first
     argument is an l10n::T family call rather than an l10n::Label;
  3. an English msgid with a '%' that the conversion grammar refuses, or a plural pair whose msgids differ in their
     conversions;
  4. an l10n::Fmt or l10n::FmtSpan call whose format is an l10n::T family call on literals and whose argument count
     differs from that msgid's conversions;
  5. a shipped pack (locale/*.po) holding a msgid the template does not.
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
MOD = ROOT / "src" / "votv-coop"
TEMPLATE = MOD / "locale" / "multivoid.pot"
# The pseudo-locale: every line the English in [[ ]], its conversions intact. Embedded like a real pack, it is how a
# run proves every surface looks its text up -- the l10n drill's translated arm, a screenshot where a line without
# brackets is one that is not -- whatever a real pack covers, and the selftest's read of every embedded pack puts each
# English msgid through the C++ conversion check. Android's tag for the same instrument; a player may pick it.
PSEUDO = MOD / "locale" / "en_XA.po"
IMGUI_H = MOD / "third_party" / "imgui" / "imgui.h"

# The files that may hold player text (the design's D6), relative to src/votv-coop/. Edited with each call-site
# sheet; a file outside it may not extract.
ALLOWLIST = [
    "include/coop/commands/command_dispatcher.h",
    "include/coop/config/config_registry_rows.inc",
    "src/coop/bug_report/report_bundle.cpp",
    "src/coop/bug_report/report_files.cpp",
    "src/coop/bug_report/report_form.cpp",
    "src/coop/commands/command_sync.cpp",
    "src/coop/comms/peer_action_feed.cpp",
    "src/coop/dispatch/event_feed.cpp",
    "src/coop/net/end_reason.cpp",
    "src/coop/player/local_body.cpp",
    "src/coop/player/nameplate.cpp",
    "src/coop/player/nick_color.cpp",
    "src/coop/player/sleep_sync.cpp",
    "src/coop/session/player_handshake.cpp",
    "src/coop/session/player_handshake_prefs.cpp",
    "src/coop/session/player_handshake_version.cpp",
    "src/coop/session/server_settings_sync.cpp",
    "src/ui/admin_panel.cpp",
    "src/ui/browser_input_screens.cpp",
    "src/ui/bug_report_pane.cpp",
    "src/ui/config_review_panel.cpp",
    "src/ui/console.cpp",
    "src/ui/dev_menu.cpp",
    "src/ui/end_reason_dialog.cpp",
    "src/ui/fonts.cpp",
    "src/ui/hud.cpp",
    "src/ui/join_curtain.cpp",
    "src/ui/link_format.cpp",
    "src/ui/loading_screen.cpp",
    "src/ui/net_stats_panel.cpp",
    "src/ui/scoreboard.cpp",
    "src/ui/server_browser_actions.cpp",
    "src/ui/server_browser_native.cpp",
    "src/ui/server_browser_panels.cpp",
    "src/ui/server_browser_rows.cpp",
    "src/ui/server_settings_pane.cpp",
    "src/ui/skins_panel.cpp",
    "src/ui/voice_icons.cpp",
    "src/ui/voice_panel.cpp",
    "src/ui/world_rules_panel.cpp",
]
# The layer itself, which looks strings up on purpose and extracts nothing.
EXEMPT_DIRS = ("src/l10n/", "include/l10n/")

EXTRACT = {"l10n::T": ("id",), "l10n::Tc": ("ctx", "id"), "l10n::Tn": ("id", "plural", None),
           "L10N_MARK": ("id",), "L10N_MARK_C": ("ctx", "id"), "L10N_MARK_N": ("id", "plural")}
T_FAMILY = ("l10n::T", "l10n::Tc", "l10n::Tn")

HEADER = """# The Multivoid interface's translation template. Generated by .github/ci/l10n_pot.py; never edited by hand.
# A translation is a copy of this file named <ll_CC>.po (zh_CN.po), with msgstr filled in.
msgid ""
msgstr ""
"Project-Id-Version: Multivoid\\n"
"Content-Type: text/plain; charset=UTF-8\\n"
"Content-Transfer-Encoding: 8bit\\n"
"Plural-Forms: nplurals=INTEGER; plural=EXPRESSION;\\n"
"""


# ---- tokens ------------------------------------------------------------------------------------------------

TOKEN = re.compile(r"""
    (?P<comment>//[^\n]*|/\*.*?\*/)
  | (?P<raw>(?:u8|u|U|L)?R"(?P<delim>[^()\\ ]{0,16})\((?P<rawbody>.*?)\)(?P=delim)")
  | (?P<string>(?:u8|u|U|L)?"(?:[^"\\\n]|\\.)*")
  | (?P<char>(?:u8|u|U|L)?'(?:[^'\\\n]|\\.)*')
  | (?P<ident>[A-Za-z_][A-Za-z_0-9]*(?:::[A-Za-z_][A-Za-z_0-9]*)*)
  | (?P<punct>[()\[\]{},;])
  | (?P<other>\S)
""", re.S | re.X)


def decode(literal):
    """A narrow C++ string literal's bytes, as the compiler decodes them (the escapes our sources use)."""
    body = literal[literal.index('"') + 1:-1]
    out = bytearray()
    i = 0
    simple = {"n": 10, "t": 9, "r": 13, "\\": 92, '"': 34, "'": 39, "a": 7, "b": 8, "f": 12, "v": 11, "0": 0}
    while i < len(body):
        c = body[i]
        if c != "\\":
            out += c.encode("utf-8")
            i += 1
            continue
        e = body[i + 1]
        if e == "x":
            j = i + 2
            while j < len(body) and body[j] in "0123456789abcdefABCDEF":
                j += 1
            out.append(int(body[i + 2:j], 16) & 0xFF)
            i = j
        elif e == "u" or e == "U":
            n = 4 if e == "u" else 8
            out += chr(int(body[i + 2:i + 2 + n], 16)).encode("utf-8")
            i += 2 + n
        elif e in "01234567" and not (e == "0" and (i + 2 >= len(body) or body[i + 2] not in "01234567")):
            j = i + 1
            while j < len(body) and j < i + 4 and body[j] in "01234567":
                j += 1
            out.append(int(body[i + 1:j], 8) & 0xFF)
            i = j
        else:
            out.append(simple.get(e, ord(e)))
            i += 2
    try:
        return out.decode("utf-8")
    except UnicodeDecodeError:
        return None   # bytes a test feeds on purpose: never a msgid


def tokens(text):
    for m in TOKEN.finditer(text):
        kind = m.lastgroup
        if kind in ("comment",):
            continue
        if kind == "raw":
            yield ("string", None, m.start())   # a raw string is never a msgid here
        elif kind == "string":
            lit = m.group("string")
            yield ("string", None if lit[0] in "uUL" and not lit.startswith("u8") else decode(lit), m.start())
        elif kind == "delim" or kind == "rawbody":
            continue
        else:
            yield (kind, m.group(kind), m.start())


def calls(toks):
    """(name, args, position) for every identifier followed by '(', args as token lists split at top-level commas."""
    for i, (kind, val, pos) in enumerate(toks):
        if kind != "ident" or i + 1 >= len(toks) or toks[i + 1][1] != "(":
            continue
        depth, j, args, cur = 0, i + 1, [], []
        while j < len(toks):
            k, v, _ = toks[j]
            if k == "punct" and v in "([{":
                depth += 1
                if depth > 1:
                    cur.append(toks[j])
            elif k == "punct" and v in ")]}":
                depth -= 1
                if depth == 0:
                    args.append(cur)
                    break
                cur.append(toks[j])
            elif k == "punct" and v == "," and depth == 1:
                args.append(cur)
                cur = []
            else:
                cur.append(toks[j])
            j += 1
        yield val, args, pos, i


def literal(arg):
    """The joined value of an argument made only of adjacent string literals, else None."""
    if not arg or any(k != "string" for k, _, _ in arg) or any(v is None for _, v, _ in arg):
        return None
    return "".join(v for _, v, _ in arg)


# ---- the conversion grammar (the layer's printf_check, in Python) -------------------------------------------

CONV = re.compile(r"%(?:(?P<num>[0-9]{1,3})\$)?(?P<flags>[-+ #0]*)(?P<width>[0-9]*)(?:\.(?P<prec>[0-9]*))?"
                  r"(?P<len>ll|l|z)?(?P<type>.)?")


def conversions(fmt):
    """[(argno, type, length)] or raises ValueError with the reason, for a msgid with a '%'."""
    out, numbered, i = [], None, 0
    while i < len(fmt):
        if fmt[i] != "%":
            i += 1
            continue
        if fmt[i + 1:i + 2] == "%":
            i += 2
            continue
        m = CONV.match(fmt, i)
        t = m.group("type")
        flags = m.group("flags")
        if t is None:
            raise ValueError("a conversion without its type")
        if t == "n":
            raise ValueError("a '%n' conversion")
        if t not in "diuxXofFeEgGs":
            raise ValueError("a conversion type outside d i u x X o f F e E g G s")
        if len(set(flags)) != len(flags):
            raise ValueError("a repeated flag")
        if len(m.group("width")) > 2 or (m.group("prec") or "").__len__() > 2:
            raise ValueError("a width or precision of more than two digits")
        if m.group("prec") is not None and t == "s":
            raise ValueError("a precision on %s")
        if m.group("len") and t not in "diuxXo":
            raise ValueError("a length modifier on a non-integer type")
        if "0" in flags and t == "s":
            raise ValueError("a '0' flag on %s")
        if ("+" in flags or " " in flags) and t not in "difFeEgG":
            raise ValueError("a '+' or ' ' flag on an unsigned or string type")
        if "#" in flags and t not in "xXofFeEgG":
            raise ValueError("a '#' flag on a type it has no form for")
        has = m.group("num") is not None
        if numbered is None:
            numbered = has
        elif numbered != has:
            raise ValueError("numbered and unnumbered conversions mixed")
        arg = int(m.group("num")) if has else len(out) + 1
        out.append((arg, "d" if t == "i" else t, m.group("len") or ""))
        i = m.end()
    nums = sorted(a for a, _, _ in out)
    if nums != list(range(1, len(out) + 1)):
        raise ValueError("an argument read twice or a gap in the numbers")
    if len(out) > 16:
        raise ValueError("more than 16 conversions")
    return out


def signature(fmt):
    return sorted(conversions(fmt)) if "%" in fmt else []


# ---- the scan -------------------------------------------------------------------------------------------------

def widget_names():
    text = IMGUI_H.read_text(encoding="utf-8", errors="replace")
    return set(re.findall(r"IMGUI_API\s+[\w\s\*]*?\b(\w+)\s*\(\s*const\s+char\s*\*\s*(?:label|name|str_id)\b", text))


def scan():
    entries = {}   # (ctx, id) -> {"plural": str|None, "refs": set}
    problems = []
    widgets = widget_names()
    sources = sorted(p for p in MOD.rglob("*") if p.suffix in (".cpp", ".h", ".inc") and "third_party" not in p.parts)
    for path in sources:
        rel = path.relative_to(MOD).as_posix()
        if rel.startswith(EXEMPT_DIRS):
            continue
        text = path.read_text(encoding="utf-8", errors="replace")
        toks = list(tokens(text))
        allowed = rel in ALLOWLIST
        for name, args, pos, idx in calls(toks):
            line = text.count("\n", 0, pos) + 1
            where = "%s:%d" % (rel, line)
            if name in EXTRACT:
                roles = EXTRACT[name]
                vals = {}
                for role, arg in zip(roles, args):
                    if role:
                        vals[role] = literal(arg)
                if vals.get("id") is None:
                    continue   # a non-literal argument: marked where its literal lives
                if not allowed:
                    problems.append("%s: %s with a literal in a file outside the allowlist" % (where, name))
                    continue
                key = (vals.get("ctx") or "", vals["id"])
                e = entries.setdefault(key, {"plural": None, "refs": set()})
                e["refs"].add(rel)
                if "plural" in vals and vals["plural"] is not None:
                    e["plural"] = vals["plural"]
                try:
                    a = signature(vals["id"])
                    if vals.get("plural") is not None and signature(vals["plural"]) != a:
                        problems.append("%s: a plural pair whose msgids differ in their conversions" % where)
                except ValueError as err:
                    problems.append("%s: msgid %r refused by the conversion grammar: %s" % (where, vals["id"], err))
            elif name.split("::")[-1] in widgets and name.startswith("ImGui::") and args:
                first = args[0]
                if first and first[0][0] == "ident" and first[0][1] in T_FAMILY:
                    problems.append("%s: %s takes a translated label without l10n::Label" % (where, name))
            elif name in ("l10n::Fmt", "l10n::FmtSpan") and args:
                fmt_index = 2 if name == "l10n::Fmt" else 3
                if len(args) <= fmt_index:
                    continue
                f = args[fmt_index]
                if not f or f[0][0] != "ident" or f[0][1] not in T_FAMILY:
                    continue
                inner = list(calls(f))
                if not inner:
                    continue
                iname, iargs, _, _ = inner[0]
                roles = EXTRACT.get(iname, ())
                msgid = None
                for role, arg in zip(roles, iargs):
                    if role == "id":
                        msgid = literal(arg)
                if msgid is None:
                    continue
                try:
                    want = len(conversions(msgid)) if "%" in msgid else 0
                except ValueError:
                    continue   # reported where the msgid is extracted
                have = len(args) - fmt_index - 1
                if have != want:
                    problems.append("%s: %s passes %d argument(s) for %r, which names %d" % (where, name, have, msgid, want))
    return entries, problems


def quote(s):
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\t", "\\t").replace("\r", "\\r")
    parts = s.split("\n")
    if len(parts) == 1:
        return '"%s"' % s
    lines = [p + "\\n" for p in parts[:-1]] + ([parts[-1]] if parts[-1] else [])
    return '""\n' + "\n".join('"%s"' % p for p in lines)


def render(entries):
    out = [HEADER.rstrip("\n")]
    for (ctx, msgid) in sorted(entries):
        e = entries[(ctx, msgid)]
        out.append("")
        out.append("#: " + " ".join(sorted(e["refs"])))
        if "%" in msgid:
            out.append("#, c-format")
        if ctx:
            out.append("msgctxt " + quote(ctx))
        out.append("msgid " + quote(msgid))
        if e["plural"] is not None:
            out.append("msgid_plural " + quote(e["plural"]))
            out.append('msgstr[0] ""')
            out.append('msgstr[1] ""')
        else:
            out.append('msgstr ""')
    return "\n".join(out) + "\n"


def render_pseudo(entries):
    out = ["# The pseudo-locale en_XA: every line the English in [[ ]]. Generated by .github/ci/l10n_pot.py with the",
           "# template; never edited by hand. A test instrument: a line without brackets on screen is not looked up.",
           'msgid ""', 'msgstr ""',
           '"Project-Id-Version: Multivoid\\n"',
           '"Language: en_XA\\n"',
           '"Content-Type: text/plain; charset=UTF-8\\n"',
           '"Content-Transfer-Encoding: 8bit\\n"',
           '"Plural-Forms: nplurals=2; plural=(n != 1);\\n"']
    for (ctx, msgid) in sorted(entries):
        e = entries[(ctx, msgid)]
        out.append("")
        if "%" in msgid:
            out.append("#, c-format")
        if ctx:
            out.append("msgctxt " + quote(ctx))
        out.append("msgid " + quote(msgid))
        if e["plural"] is not None:
            out.append("msgid_plural " + quote(e["plural"]))
            out.append("msgstr[0] " + quote("[[" + msgid + "]]"))
            out.append("msgstr[1] " + quote("[[" + e["plural"] + "]]"))
        else:
            out.append("msgstr " + quote("[[" + msgid + "]]"))
    return "\n".join(out) + "\n"


def pack_msgids(path):
    """The (ctx, msgid) pairs a .po file defines, by a minimal scan; validating translations is the runtime's."""
    text = path.read_text(encoding="utf-8", errors="replace")
    pairs, ctx, cur, field = set(), "", None, None
    def unq(s):
        return bytes(s[1:-1], "utf-8").decode("unicode_escape").encode("latin-1").decode("utf-8")
    for raw in text.splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("msgctxt "):
            ctx, field = unq(line[8:]), "ctx"
        elif line.startswith("msgid "):
            cur, field = unq(line[6:]), "id"
        elif line.startswith('"'):
            if field == "id":
                cur += unq(line)
            elif field == "ctx":
                ctx += unq(line)
        elif line.startswith("msgstr") or line.startswith("msgid_plural"):
            if cur is not None and field == "id" and cur != "":
                pairs.add((ctx, cur))
            if line.startswith("msgstr"):
                ctx = ""
            field = None
    return pairs


def main():
    entries, problems = scan()
    text = render(entries)
    pseudo = render_pseudo(entries)
    if "--check" in sys.argv[1:]:
        for path, want in ((TEMPLATE, text), (PSEUDO, pseudo)):
            have = path.read_text(encoding="utf-8").replace("\r\n", "\n") if path.exists() else ""
            if have != want:
                problems.append("%s is stale -- run .github/ci/l10n_pot.py" % path.relative_to(ROOT).as_posix())
        known = set(entries)
        for po in sorted((MOD / "locale").glob("*.po")):
            for pair in sorted(pack_msgids(po) - known):
                problems.append("%s holds %r, which the template does not" % (po.relative_to(ROOT).as_posix(), pair[1]))
        for p in problems:
            print("l10n_pot: " + p)
        print("l10n_pot: %s (%d entries)" % ("FAIL" if problems else "PASS", len(entries)))
        return 1 if problems else 0
    if problems:
        for p in problems:
            print("l10n_pot: " + p)
        print("l10n_pot: not written -- fix the problems above")
        return 1
    TEMPLATE.parent.mkdir(parents=True, exist_ok=True)
    TEMPLATE.write_text(text, encoding="utf-8", newline="\n")
    PSEUDO.write_text(pseudo, encoding="utf-8", newline="\n")
    print("l10n_pot: wrote %s and %s (%d entries)" % (TEMPLATE.relative_to(ROOT).as_posix(),
                                                      PSEUDO.relative_to(ROOT).as_posix(), len(entries)))
    return 0


if __name__ == "__main__":
    sys.exit(main())
