# votv-coop/sources.cmake -- the DLL's translation units, one per line.
#
# Extracted from CMakeLists.txt when that file reached the 800-line cap: the build
# CONFIGURATION (toolchain, third-party targets, the version stamp, the link and install
# rules) and the LIST OF SOURCES are two concerns, and the list is the half that grows with
# every feature. CMakeLists.txt includes this and expands VOTVCOOP_SOURCES.
#
# Order follows the principle-7 split -- bootstrap and loader, then src/ue_wrap/ (engine
# wrapper), then src/coop/ (gameplay and network), then src/ui/ and src/harness/, with the
# resource scripts last.

set(VOTVCOOP_SOURCES
    src/bootstrap/dllmain.cpp
    src/bootstrap/boot.cpp
    src/bootstrap/refuse_dialog.cpp
    src/loader/cppmod_entry.cpp
    src/loader/cppmod_stubs.asm
    src/ue_wrap/core/log.cpp
    src/ue_wrap/core/paths.cpp
    src/ue_wrap/core/sig_scan.cpp
    src/ue_wrap/core/gc_pin.cpp
    src/ue_wrap/core/reflection.cpp
    src/ue_wrap/core/uobject_listeners.cpp
    src/ue_wrap/core/object_index.cpp
    src/ue_wrap/core/reflection_props.cpp
    src/ue_wrap/core/asset_load.cpp
    src/ue_wrap/core/engine_heap.cpp
    src/ue_wrap/core/hook.cpp
    src/ue_wrap/core/hook_drill.cpp
    src/ue_wrap/core/game_thread.cpp
    src/ue_wrap/core/pe_detour.cpp
    src/ue_wrap/core/pe_diag.cpp
    src/ue_wrap/engine/spawn_gate.cpp
    src/ue_wrap/core/ufunction_hook.cpp
    src/ue_wrap/core/vm_dispatch.cpp
    src/ue_wrap/engine/engine.cpp
    src/ue_wrap/engine/engine_save.cpp
    src/ue_wrap/actors/begin_equipment.cpp
    src/ue_wrap/actors/floppy_disc.cpp
    src/ue_wrap/actors/hook.cpp
    src/ue_wrap/world/keyed_objects.cpp
    src/coop/items/hook_sync.cpp
    src/coop/items/hook_anchor.cpp
    src/coop/items/hook_prop_claim.cpp
    src/coop/items/hook_constraint.cpp
    src/ue_wrap/engine/save_capture.cpp
    src/ue_wrap/engine/engine_audio.cpp
    src/ue_wrap/engine/engine_bones.cpp
    src/ue_wrap/engine/engine_component.cpp
    src/ue_wrap/engine/engine_mainplayer.cpp
    src/ue_wrap/engine/scs_rig.cpp
    src/ue_wrap/engine/engine_playerragdoll.cpp
    src/ue_wrap/engine/engine_attach.cpp
    src/ue_wrap/devices/door.cpp
    src/ue_wrap/devices/base_window.cpp
    src/ue_wrap/devices/grime.cpp
    src/ue_wrap/world/daynightcycle.cpp
    src/ue_wrap/world/skysphere.cpp
    src/ue_wrap/world/directionalwind.cpp
    src/ue_wrap/devices/lightswitch.cpp
    src/ue_wrap/devices/garage.cpp
    src/ue_wrap/devices/appliance.cpp
    src/ue_wrap/devices/power_control.cpp
    src/ue_wrap/devices/atv.cpp
    src/ue_wrap/devices/atv_condition.cpp
    src/ue_wrap/devices/drone.cpp
    src/ue_wrap/devices/windturbine.cpp
    src/ue_wrap/devices/door_box.cpp
    src/ue_wrap/desk/device_screen.cpp
    src/ue_wrap/desk/space_renderer.cpp
    src/ue_wrap/desk/console_desk.cpp
    src/ue_wrap/desk/comp_pane.cpp
    src/ue_wrap/desk/coords_panel.cpp
    src/ue_wrap/desk/dish.cpp
    src/ue_wrap/desk/tape_caddy.cpp
    src/ue_wrap/devices/floppy_slot.cpp
    src/ue_wrap/devices/laptop.cpp
    src/ue_wrap/devices/portable_pc.cpp
    src/ue_wrap/devices/floppybox.cpp
    src/ue_wrap/devices/serverbox.cpp
    src/ue_wrap/desk/desk_audio.cpp
    src/ue_wrap/desk/phys_mods.cpp
    src/ue_wrap/desk/drive_chain.cpp
    src/ue_wrap/desk/daily_task.cpp
    src/ue_wrap/actors/sleep.cpp
    src/ue_wrap/world/email.cpp
    src/ue_wrap/devices/passwordlock.cpp
    src/ue_wrap/core/trace.cpp
    src/ue_wrap/actors/wisp.cpp
    src/ue_wrap/actors/swinger.cpp
    src/ue_wrap/engine/engine_pawn.cpp
    src/ue_wrap/engine/world_identity.cpp
    src/ue_wrap/engine/engine_nav.cpp
    src/ue_wrap/engine/engine_widget.cpp
    src/ue_wrap/engine/umg_build.cpp
    src/ue_wrap/engine/save_browser.cpp
    src/ue_wrap/engine/gvas_meta.cpp
    src/ue_wrap/core/reflected_offset.cpp
    src/ue_wrap/core/call.cpp
    src/ue_wrap/core/fname_utils.cpp
    src/ue_wrap/core/ftext_utils.cpp
    src/ue_wrap/core/fstring_utils.cpp
    src/ue_wrap/core/field_io.cpp
    src/ue_wrap/desk/signal_dynamic.cpp
    src/ue_wrap/desk/meadow_store.cpp
    src/ue_wrap/desk/saved_signals.cpp
    src/ue_wrap/actors/puppet.cpp
    src/ue_wrap/actors/puppet_spawn.cpp
    src/ue_wrap/actors/kerfur.cpp
    src/ue_wrap/world/votv_lib.cpp
    src/ue_wrap/world/economy.cpp
    src/ue_wrap/world/order_economy.cpp
    src/ue_wrap/world/store_catalog.cpp
    src/ue_wrap/actors/prop.cpp
    src/ue_wrap/actors/vitals.cpp
    src/ue_wrap/world/game_rules.cpp
    src/ue_wrap/engine/spawn_menu.cpp
    src/ue_wrap/engine/level_travel.cpp
    src/coop/player/movement_ledger.cpp
    src/coop/player/remote_player.cpp
    src/coop/player/remote_player_ragdoll.cpp
    src/coop/player/client_model.cpp
    src/coop/player/skin_effects.cpp
    src/coop/player/skin_registry.cpp
    src/coop/player/local_body.cpp
    src/coop/props/remote_prop.cpp
    src/coop/props/unresolved_pose_ledger.cpp
    src/coop/props/remote_prop_convert.cpp
    src/coop/props/remote_prop_destroy.cpp
    src/coop/props/remote_prop_physics.cpp
    src/coop/save/save_guard.cpp
    src/coop/world/balance_sync.cpp
    src/coop/world/daily_task_sync.cpp
    src/coop/save/save_block.cpp
    src/coop/save/save_button_disable.cpp
    src/ui/multiplayer_menu.cpp
    src/coop/player/nameplate.cpp
    src/coop/player/nick_color.cpp
    src/coop/player/nickname_arbiter.cpp
    src/coop/player/hand_item.cpp
    src/coop/comms/chat_feed.cpp
    src/coop/comms/chat_log.cpp
    src/coop/comms/chat_bubbles.cpp
    src/coop/comms/peer_action_feed.cpp
    src/coop/dispatch/event_feed.cpp
    src/coop/dispatch/event_dispatch_entity.cpp
    src/coop/dispatch/event_dispatch_intent.cpp
    src/coop/dispatch/event_dispatch_signal.cpp
    src/coop/dispatch/event_dispatch_state.cpp
    src/coop/dispatch/event_dispatch_world.cpp
    src/coop/comms/chat_sync.cpp
    src/coop/interactables/turbine_sync.cpp
    src/coop/interactables/interactable_sync.cpp
    src/coop/creatures/kerfur_convert.cpp
    src/coop/creatures/kerfur_convert_client.cpp
    src/coop/creatures/kerfur_convert_host.cpp
    src/coop/creatures/kerfur_command.cpp
    src/coop/creatures/kerfur_menu_input.cpp
    src/coop/creatures/kerfur_entity.cpp
    src/coop/creatures/kerfur_form_assembler.cpp
    src/coop/creatures/kerfur_prop_adoption.cpp
    src/coop/creatures/kerfur_reconcile.cpp
    src/coop/interactables/keypad_sync.cpp
    src/coop/world/time_sync.cpp
    src/coop/world/sky_sync.cpp
    src/coop/interactables/power_sync.cpp
    src/coop/interactables/atv_sync.cpp
    src/coop/interactables/atv_condition_sync.cpp
    src/coop/interactables/atv_corrector.cpp
    src/coop/interactables/atv_hit_guard.cpp
    src/coop/interactables/drone_sync.cpp
    src/coop/items/coingun_sync.cpp
    src/coop/items/coingun_arbiter.cpp
    src/coop/items/coingun_collect.cpp
    src/coop/items/order_sync.cpp
    src/coop/world/firefly_sync.cpp
    src/coop/world/spawn_authority.cpp
    src/coop/world/event_cue_sync.cpp
    src/coop/world/event_fire_sync.cpp
    src/coop/world/event_active_sync.cpp
    src/coop/world/alarm_sync.cpp
    src/coop/interactables/serverbox_sync.cpp
    src/coop/interactables/window_sync.cpp
    src/coop/interactables/grime_sync.cpp
    src/coop/session/player_handshake.cpp
    src/coop/session/player_handshake_prefs.cpp
    src/coop/session/player_handshake_nick.cpp
    src/coop/session/player_handshake_roster.cpp
    src/coop/session/player_handshake_version.cpp
    src/coop/props/grab_observer.cpp
    src/coop/player/item_activate.cpp
    src/coop/player/player_damage.cpp
    src/coop/player/ragdoll_gate.cpp
    src/coop/player/death_revive.cpp
    src/coop/player/skin_preview.cpp
    src/coop/player/flashlight_click_sound.cpp
    src/coop/props/prop_sound.cpp
    src/coop/items/inventory_pickup_sync.cpp
    src/coop/session/shutdown.cpp
    src/coop/player/players_registry.cpp
    src/coop/element/mirror_defer.cpp
    src/ui/join_curtain.cpp
    src/coop/creatures/npc_adoption.cpp
    src/coop/creatures/npc_mirror.cpp
    src/coop/creatures/npc_pose_drive.cpp
    src/coop/creatures/npc_pose_host.cpp
    src/coop/creatures/npc_sync.cpp
    src/coop/creatures/npc_sync_install.cpp
    src/coop/creatures/npc_world_enum.cpp
    src/coop/creatures/piramid_sync.cpp
    src/coop/creatures/roach_sync.cpp
    src/coop/creatures/owner_entity_sync.cpp
    src/coop/world/world_actor_sync.cpp
    src/coop/world/world_actor_mirror.cpp
    src/coop/props/prop_echo_suppress.cpp
    src/coop/props/pile_spawn_bind.cpp
    src/coop/props/snapshot_census.cpp
    src/coop/props/save_identity_map.cpp
    src/coop/props/save_identity_bind.cpp
    src/coop/dev/force_overdestroy_test.cpp
    src/coop/props/prop_census.cpp
    src/coop/props/prop_element_tracker.cpp
    src/coop/props/prop_key_index.cpp
    src/coop/props/prop_destroy_seam.cpp
    src/coop/props/prop_lifecycle.cpp
    src/coop/props/prop_container_extract.cpp
    src/coop/props/prop_drop_intent.cpp
    src/coop/props/prop_snapshot.cpp
    src/coop/props/prop_save_data.cpp
    src/coop/props/prop_stick_sync.cpp
    src/coop/props/prop_synth_key.cpp
    src/coop/props/prop_fresh_spawn.cpp
    src/coop/props/prop_wire_parity.cpp
    src/coop/props/remote_prop_spawn.cpp
    src/coop/props/join_membership_sweep.cpp
    src/coop/session/world_load_episode.cpp
    src/coop/interactables/garbage_sync.cpp
    src/coop/props/host_spawn_watcher.cpp
    src/coop/props/trash_channel.cpp
    src/coop/props/trash_grab_intent.cpp
    src/coop/props/trash_collect_sync.cpp
    src/coop/props/trash_use_intercept.cpp
    src/coop/props/trash_pile_sync.cpp
    src/coop/props/trash_proxy.cpp
    src/coop/props/native_pile_mirror.cpp
    src/coop/player/puppet_carry_drive.cpp
    src/coop/props/trash_clump_pose_stream.cpp
    src/coop/props/prop_drive_host.cpp
    src/coop/props/prop_drive_stream.cpp
    src/coop/world/weather_sync.cpp
    src/coop/world/weather_fog.cpp
    src/coop/world/weather_lightning.cpp
    src/coop/world/weather_rain.cpp
    src/coop/world/weather_event_births.cpp
    src/coop/world/weather_redsky.cpp
    src/coop/config/config.cpp
    src/coop/text/utf8_codec.cpp
    src/coop/text/case_fold.cpp
    src/coop/text/repertoire.cpp
    src/coop/config/config_example.cpp
    src/coop/config/config_ini_write.cpp
    src/coop/config/config_registry.cpp
    src/coop/config/config_selftest.cpp
    src/coop/config/config_review.cpp
    src/coop/element/element.cpp
    src/coop/element/object_scan_hub.cpp
    src/coop/element/element_deleter.cpp
    src/coop/element/registry.cpp
    src/coop/element/intent_authority.cpp
    src/coop/element/world_actor.cpp
    src/coop/element/quiescence_drain.cpp
    src/coop/element/identity_create.cpp
    src/coop/element/identity_destroy.cpp
    src/coop/element/portable_identity.cpp
    src/ue_wrap/core/component_calls.cpp
    src/coop/net/peer_admission.cpp
    src/coop/net/peer_admission_selftest.cpp
    src/coop/net/lobby_password.cpp
    src/coop/net/peer_identity.cpp
    src/coop/net/session.cpp
    src/coop/net/session_receive.cpp
    src/coop/net/session_streams.cpp
    src/coop/net/net_stats.cpp
    src/coop/net/session_npc.cpp
    src/coop/net/session_worldactor.cpp
    src/coop/net/session_trashcarry.cpp
    src/coop/net/session_propdrive.cpp
    src/coop/net/session_start.cpp
    src/coop/net/session_status.cpp
    src/coop/net/session_relay.cpp
    src/coop/net/send_backlog.cpp
    src/coop/net/ice_config.cpp
    src/coop/net/signaling_client.cpp
    src/coop/net/http_client.cpp
    src/coop/net/lobby_client.cpp
    src/coop/net/lobby_announcer.cpp
    src/coop/save/save_transfer.cpp
    src/coop/save/save_indicator_suppress.cpp
    src/coop/session/session_manager.cpp
    src/coop/session/join_progress.cpp
    src/coop/session/join_seed.cpp
    src/coop/session/net_pump.cpp
    src/coop/player/puppet_drive.cpp
    src/coop/props/registry_reaper.cpp
    src/coop/session/pause_guard.cpp
    src/coop/session/subsystems.cpp
    src/coop/player/local_streams.cpp
    src/coop/interactables/device_occupancy.cpp
    src/coop/interactables/console_state_sync.cpp
    src/coop/interactables/desk_cursor_sync.cpp
    src/coop/interactables/desk_input_sync.cpp
    src/coop/interactables/deck_play_sync.cpp
    src/coop/interactables/physmods_sync.cpp
    src/coop/interactables/drive_sync.cpp
    src/coop/interactables/drive_rack_sync.cpp
    src/coop/interactables/desk_snd_fx.cpp
    src/coop/interactables/desk_sim_sync.cpp
    src/coop/interactables/dish_sync.cpp
    src/coop/interactables/tape_caddy_sync.cpp
    src/coop/interactables/laptop_sync.cpp
    src/coop/interactables/laptop_buffer_sync.cpp
    src/coop/interactables/floppy_slot_entry.cpp
    src/coop/interactables/floppy_slot_sync.cpp
    src/coop/interactables/floppybox_sync.cpp
    src/coop/interactables/signal_catch_sync.cpp
    src/coop/player/sleep_sync.cpp
    src/coop/creatures/wisp_attack_sync.cpp
    src/coop/creatures/wisp_grab_hold.cpp
    src/coop/creatures/wisp_tear_mirror.cpp
    src/coop/items/player_inventory_sync.cpp
    src/coop/items/inventory_wire.cpp
    src/coop/items/save_record_wire.cpp
    src/coop/props/container_contents_sync.cpp
    src/coop/dev/delivery_census_probe.cpp
    src/coop/dev/store_table_probe.cpp
    src/coop/dev/order_selftest.cpp
    src/ue_wrap/actors/inventory.cpp
    src/ue_wrap/actors/save_record.cpp
    src/coop/world/email_sync.cpp
    src/coop/net/blob_chunks.cpp
    src/coop/interactables/signal_wire.cpp
    src/coop/interactables/meadow_db_sync.cpp
    src/coop/interactables/signal_sync.cpp
    src/coop/interactables/comp_sync.cpp
    src/coop/voice/voice_chat.cpp
    src/coop/voice/voice_capture.cpp
    src/coop/voice/voice_playback.cpp
    src/coop/net/session_voice.cpp
    src/ui/voice_icons.cpp
    src/ui/voice_panel.cpp
    src/coop/dev/add_points.cpp
    src/coop/dev/spawn_order_probe.cpp
    src/coop/dev/prop_birth_key_probe.cpp
    src/coop/dev/spawn_match_probe.cpp
    src/coop/dev/native_text_probe.cpp
    src/coop/dev/eid_lifetime_trace.cpp
    src/coop/dev/join_window_pos_trace.cpp
    src/coop/dev/rng_roll_census.cpp
    src/coop/dev/death_write_diff.cpp
    src/coop/dev/desk_diag.cpp
    src/coop/dev/container_selftest.cpp
    src/coop/dev/drive_selftest.cpp
    src/coop/dev/hand_drop_selftest.cpp
  src/coop/dev/floppy_selftest.cpp
    src/coop/dev/floppy_selftest_world.cpp
    src/coop/dev/hookdrag_selftest.cpp
    src/coop/dev/roster_token_selftest.cpp
    src/coop/dev/kerfur_census.cpp
    src/coop/dev/puppet_head_probe.cpp
    src/coop/dev/wire_census.cpp
    src/coop/input/input_owner.cpp
    src/coop/dev/perf_probe.cpp
    src/coop/dev/input_focus_probe.cpp
    src/coop/dev/leak_probe.cpp
    src/coop/dev/heap_probe.cpp
    src/coop/dev/inventory_probe.cpp
    src/coop/dev/live_store_readout.cpp
    src/coop/dev/drone_probe.cpp
    src/coop/dev/gnatives_probe.cpp
    src/coop/dev/native_pile_inert_probe.cpp
    src/coop/dev/client_model_probe.cpp
    src/coop/dev/atv_eject_drill.cpp
    src/coop/dev/atv_probe.cpp
    src/coop/dev/atv_tire_probe.cpp
    src/coop/dev/pinecone_probe.cpp
    src/coop/dev/sleep_probe.cpp
    src/coop/dev/event_trigger.cpp
    src/coop/dev/event_force.cpp
    src/coop/dev/light_group_census.cpp
    src/coop/dev/lightswitch_probe.cpp
    src/coop/dev/keypad_probe.cpp
    src/coop/dev/door_probe.cpp
    src/coop/dev/save_probe.cpp
    src/coop/dev/native_ui_probe.cpp
    src/coop/dev/worldless_frames.cpp
    src/coop/dev/dev_gate.cpp
    src/coop/dev/director/player_context.cpp
    src/coop/dev/director/control_manager.cpp
    src/coop/dev/director/proc_walkgrab.cpp
    src/coop/dev/director/director_run.cpp
    src/coop/dev/director/container_take_probe.cpp
    src/coop/dev/director/dup_verifier.cpp
    src/coop/dev/force_weather.cpp
    src/coop/dev/weather_probe.cpp
    src/coop/dev/freecam.cpp
    src/coop/dev/flashlight_setup.cpp
    src/coop/dev/pos_hud.cpp
    src/coop/dev/restore_vitals.cpp
    src/coop/dev/vitals_keepalive.cpp
    src/coop/dev/set_clock.cpp
    src/coop/dev/spawn_menu_unlock.cpp
    src/coop/dev/spawn_npc.cpp
    src/coop/dev/kerfur_toggle.cpp
    src/coop/session/teleport_client.cpp
    src/coop/dev/menu_proceed.cpp
    src/coop/dev/object_overlay.cpp
    src/coop/dev/ragdoll_bone_overlay.cpp
    src/ui/imgui_overlay.cpp
    src/ui/overlay_diag.cpp
    src/ui/overlay_test_arm.cpp
    src/ui/overlay_cursor.cpp
    src/ui/style.cpp
    src/ui/overlay_backend.cpp
    src/ui/overlay_backend_dx11.cpp
    src/ui/overlay_backend_dx12.cpp
    src/ui/overlay_backend_dx12_capture.cpp
    src/ui/dev_menu.cpp
    src/ui/skins_panel.cpp
    src/ui/admin_panel.cpp
    src/ui/world_rules_panel.cpp
    src/ui/scoreboard.cpp
    src/ui/link_format.cpp
    src/ui/server_browser.cpp
    src/ui/native_screen.cpp
    src/ui/native_text_field.cpp
    src/ui/host_window_native.cpp
    src/ui/host_session_choices.cpp
    src/ui/host_session_settings.cpp
    src/ui/browser_input_screens.cpp
    src/ui/server_browser_actions.cpp
    src/ui/server_browser_native.cpp
    src/ui/server_browser_panels.cpp
    src/ui/server_browser_rows.cpp
    src/ui/server_browser_surface.cpp
    src/ui/server_browser_selftest.cpp
    src/ui/boot_warning_dialog.cpp
    src/ui/config_review_panel.cpp
    src/ui/connect_failed_dialog.cpp
    src/ui/menu_sfx.cpp
    src/ui/host_save_picker.cpp
    src/ui/loading_screen.cpp
    src/ui/console.cpp
    src/ui/hud.cpp
    src/ui/net_stats_panel.cpp
    src/ui/chat_input.cpp
    src/ui/chat_view.cpp
    src/coop/text/novelty_ledger.cpp
    src/ui/fonts.cpp
    src/ui/atlas_watch.cpp
    src/ui/scale.cpp
    resources/fonts.rc
    src/coop/player/roster.cpp
    src/coop/player/roster_ledger.cpp
    src/coop/moderation/ban_list.cpp
    src/coop/moderation/moderation.cpp
    src/coop/moderation/seen_players.cpp
    src/harness/harness.cpp
    src/harness/session_runtime.cpp
    src/harness/harness_diag.cpp
    src/harness/autotest/autotest_grab.cpp
    src/harness/autotest/autotest_chippile.cpp
    src/harness/autotest/autotest_clump.cpp
    src/harness/autotest/autotest_flashlight.cpp
    src/harness/autotest/autotest_tracker_selftest.cpp
    src/harness/autotest/autotest_weather.cpp
    src/harness/autotest/autotest_seeddrill.cpp
    src/harness/autotest/autotest_scanparity.cpp
    src/harness/autotest/autotest_worldctx.cpp
    src/harness/autotest/autotest_worldrules.cpp
    src/harness/autotest/autotest_config.cpp
    src/harness/autotest/autotest_dispatch.cpp
    src/harness/autotest/autotest_damage.cpp
    src/harness/autotest/autotest_dmghazard.cpp
    src/harness/autotest/autotest_playerdmg.cpp
    src/harness/autotest/autotest_death.cpp
    src/harness/autotest/autotest_puppetframe.cpp
    src/harness/autotest/autotest_ragdoll.cpp
    src/harness/autotest/autotest_ragdoll_spawn_probe.cpp
    src/harness/autotest/autotest_menutravel_probe.cpp
    src/harness/autotest/autotest_reloadchurn.cpp
    src/harness/autotest/autotest_islive_drill.cpp
    src/harness/autotest/autotest_fog_probe.cpp
    src/harness/autotest/autotest_hud_tint.cpp
    src/harness/autotest/autotest_eventfire.cpp
    src/harness/autotest/autotest_eventforce.cpp
    src/harness/autotest/autotest_cueforce.cpp
    src/harness/autotest/autotest_alarmforce.cpp
    src/harness/autotest/autotest_piramidforce.cpp
    src/harness/autotest/autotest_wisplane.cpp
    src/harness/autotest/autotest_navprobe.cpp
    src/harness/autotest/autotest_kwisp_probe.cpp
    src/harness/autotest/autotest_pauseguard.cpp
    src/harness/autotest/autotest_move_osc.cpp
    src/harness/autotest/autotest_saveui.cpp
    src/ui/input_focus.cpp
    src/harness/screenshot.cpp
    src/harness/mod_environment.cpp
    src/harness/sdk_check.cpp
)
